export type KategorieSleutel =
  | "elektries"
  | "hardeware"
  | "konstruksie"
  | "verf"
  | "loodgieter"
  | "gas";

export interface Kategorie {
  sleutel: KategorieSleutel;
  naam: string;
  naamEn: string;
  beskrywing: string;
  ikoon: string;
}

export interface Produk {
  id: string;
  sku: string;
  naam: string;
  naamEn?: string;
  kategorie: KategorieSleutel;
  handelsmerk: string;
  prys: number; // BTW-ingesluit, in ZAR
  voorraad: boolean;
  topverkoper?: boolean;
  beskrywing: string;
  beskrywingEn?: string;
  beeldUrl?: string;
}

export const KATEGORIEE: Kategorie[] = [
  { sleutel: "elektries",  naam: "Elektries",          naamEn: "Electrical",        beskrywing: "Kabels, kragpunte, beligting, kragpaneel-toebehore en voorafbetaalde meters.", ikoon: "⚡" },
  { sleutel: "hardeware",  naam: "Hardeware",           naamEn: "Hardware",          beskrywing: "Skroewe, boute, slotte, skarniere en alledaagse hardewareware.", ikoon: "🔩" },
  { sleutel: "konstruksie",naam: "Konstruksie & DHS",   naamEn: "Construction & DIY",beskrywing: "Sement, gips, hout en alles vir die doen-dit-self projek.", ikoon: "🧱" },
  { sleutel: "verf",       naam: "Verf & Gereedskap",   naamEn: "Paint & Tools",     beskrywing: "Verfmenging op bestelling, kwaste, rollers en kragtoerusting.", ikoon: "🎨" },
  { sleutel: "loodgieter", naam: "Loodgieter",          naamEn: "Plumbing",          beskrywing: "Pype, koppelstukke, krane en geyser-toebehore.", ikoon: "🚰" },
  { sleutel: "gas",        naam: "Gasprodukte",         naamEn: "Gas Products",      beskrywing: "LP-gas hervullings, reguleerders, pype en gastoestelle.", ikoon: "🔥" },
];

export const kategorieNaam = (s: KategorieSleutel, lang: "af" | "en" = "af") => {
  const k = KATEGORIEE.find((k) => k.sleutel === s);
  return lang === "en" ? (k?.naamEn ?? s) : (k?.naam ?? s);
};

/** Mock-katalogus — verteenwoordigend van 'n tipiese SA hardeware-winkel se rakke. */
export const PRODUKTE: Produk[] = [
  // ── Elektries ──
  { id: "e1", sku: "EL-CAB-25",   naam: "Surfix Kabel 2.5mm² (per meter)",          naamEn: "Surfix Cable 2.5mm² (per metre)",           kategorie: "elektries",   handelsmerk: "Aberdare",       prys: 18.5,   voorraad: true,  topverkoper: true,  beskrywing: "Twin & earth surfix kabel vir huishoudelike bedrading.",                            beskrywingEn: "Twin & earth surfix cable for domestic wiring.",                               beeldUrl: "https://images.pexels.com/photos/28286038/pexels-photo-28286038.jpeg" },
  { id: "e2", sku: "EL-DB-8W",    naam: "Verdeelbord 8-Weg Oppervlak",               naamEn: "Distribution Board 8-Way Surface",          kategorie: "elektries",   handelsmerk: "CBI",            prys: 489.0,  voorraad: true,                      beskrywing: "8-weg verdeelbord met hoofskakelaar, SABS goedgekeur.",                           beskrywingEn: "8-way distribution board with main switch, SABS approved.",                    beeldUrl: "https://images.pexels.com/photos/5767595/pexels-photo-5767595.jpeg" },
  { id: "e3", sku: "EL-PLUG-16",  naam: "Muurprop 16A Enkel met Skakelaar",          naamEn: "Wall Plug 16A Single with Switch",          kategorie: "elektries",   handelsmerk: "Crabtree",       prys: 129.9,  voorraad: true,  topverkoper: true,  beskrywing: "Wit enkel kragpunt, 4x4 met skakelaar.",                                          beskrywingEn: "White single power point, 4x4 with switch.",                                   beeldUrl: "https://images.pexels.com/photos/32497160/pexels-photo-32497160.jpeg" },
  { id: "e4", sku: "EL-LED-9W",   naam: "LED Gloeilamp 9W B22 (Koel Wit)",           naamEn: "LED Bulb 9W B22 (Cool White)",              kategorie: "elektries",   handelsmerk: "Eurolux",        prys: 39.95,  voorraad: true,                      beskrywing: "Energiebesparende LED-lamp, 6500K, 806 lumen.",                                   beskrywingEn: "Energy-saving LED lamp, 6500K, 806 lumens.",                                   beeldUrl: "https://images.pexels.com/photos/3946250/pexels-photo-3946250.jpeg" },
  { id: "e5", sku: "EL-PPM-STS6", naam: "Voorafbetaalde Meter STS (Enkele Fase)",    naamEn: "Prepaid Meter STS (Single Phase)",          kategorie: "elektries",   handelsmerk: "Conlog",         prys: 1899.0, voorraad: false,                     beskrywing: "STS-voldoende voorafbetaalde kragmeter — installasie aanbeveel.",                 beskrywingEn: "STS-compliant prepaid power meter — installation recommended.",                 beeldUrl: "https://images.pexels.com/photos/7541342/pexels-photo-7541342.jpeg" },
  { id: "e6", sku: "EL-EXT-10",   naam: "Verlengkoord 10m 3-Punt",                   naamEn: "Extension Cord 10m 3-Pin",                  kategorie: "elektries",   handelsmerk: "Waco",           prys: 219.0,  voorraad: true,                      beskrywing: "Swaardiens verlengkoord met oorlading-beskerming.",                               beskrywingEn: "Heavy-duty extension cord with overload protection.",                           beeldUrl: "https://images.pexels.com/photos/3616742/pexels-photo-3616742.jpeg" },
  { id: "e7", sku: "EL-EARTH-LK", naam: "Aardlek-eenheid 30mA 2-Pool",               naamEn: "Earth Leakage Unit 30mA 2-Pole",            kategorie: "elektries",   handelsmerk: "CBI",            prys: 349.0,  voorraad: true,                      beskrywing: "Aardlek-beskermingseenheid vir verdeelbord.",                                     beskrywingEn: "Earth leakage protection unit for distribution board.",                         beeldUrl: "https://images.pexels.com/photos/31701039/pexels-photo-31701039.jpeg" },
  { id: "e8", sku: "EL-FLOOD-30", naam: "LED Spuitlig 30W met Sensor",                naamEn: "LED Flood Light 30W with Sensor",           kategorie: "elektries",   handelsmerk: "Eurolux",        prys: 279.0,  voorraad: true,                      beskrywing: "Buitemuur spuitlig met PIR bewegingsensor.",                                      beskrywingEn: "Outdoor flood light with PIR motion sensor.",                                   beeldUrl: "https://images.pexels.com/photos/3946161/pexels-photo-3946161.jpeg" },

  // ── Hardeware ──
  { id: "h1", sku: "HW-SCR-4X40",  naam: "Spaanplaatskroewe 4x40mm (200 pak)",      naamEn: "Wood Screws 4x40mm (200 pack)",             kategorie: "hardeware",   handelsmerk: "Vermeer",        prys: 89.9,   voorraad: true,  topverkoper: true,  beskrywing: "Gegalvaniseerde spaanplaatskroewe, Pozi-kop.",                                    beskrywingEn: "Galvanised chipboard screws, Pozi head.",                                      beeldUrl: "https://images.pexels.com/photos/5583069/pexels-photo-5583069.jpeg" },
  { id: "h2", sku: "HW-HINGE-100", naam: "Skarnier 100mm Vlinder (Paar)",            naamEn: "Butt Hinge 100mm (Pair)",                   kategorie: "hardeware",   handelsmerk: "Yale",           prys: 64.5,   voorraad: true,                      beskrywing: "Vlekvrye staal skarniere vir binnedeure.",                                        beskrywingEn: "Stainless steel butt hinges for interior doors.",                               beeldUrl: "https://images.pexels.com/photos/28119515/pexels-photo-28119515.jpeg" },
  { id: "h3", sku: "HW-PAD-50",    naam: "Hangslot 50mm Gehard",                     naamEn: "Padlock 50mm Hardened",                     kategorie: "hardeware",   handelsmerk: "Yale",           prys: 149.0,  voorraad: true,                      beskrywing: "Geharde staal hangslot met 3 sleutels.",                                          beskrywingEn: "Hardened steel padlock with 3 keys.",                                          beeldUrl: "https://images.pexels.com/photos/36740854/pexels-photo-36740854.jpeg" },
  { id: "h4", sku: "HW-CHAIN-6",   naam: "Kettingdraad 6mm (per meter)",             naamEn: "Chain 6mm (per metre)",                     kategorie: "hardeware",   handelsmerk: "Generies",       prys: 32.0,   voorraad: true,                      beskrywing: "Gegalvaniseerde ketting, verkoop per meter.",                                     beskrywingEn: "Galvanised chain, sold per metre.",                                            beeldUrl: "https://images.pexels.com/photos/4006805/pexels-photo-4006805.jpeg" },
  { id: "h5", sku: "HW-LOCK-3L",   naam: "3-Hefboom Insteekslot",                    naamEn: "3-Lever Mortice Lock",                      kategorie: "hardeware",   handelsmerk: "Union",          prys: 219.0,  voorraad: true,                      beskrywing: "Insteekslot vir houtdeure, SABS goedgekeur.",                                     beskrywingEn: "Mortice lock for wooden doors, SABS approved.",                                beeldUrl: "https://images.pexels.com/photos/9554231/pexels-photo-9554231.jpeg" },
  { id: "h6", sku: "HW-TAPE-PTFE", naam: "PTFE Verseëlband (Wit)",                   naamEn: "PTFE Thread Seal Tape (White)",             kategorie: "hardeware",   handelsmerk: "Generies",       prys: 9.95,   voorraad: true,                      beskrywing: "Draadverseëlband vir loodgieterswerk.",                                           beskrywingEn: "Thread seal tape for plumbing work.",                                          beeldUrl: "https://images.pexels.com/photos/29301874/pexels-photo-29301874.jpeg" },

  // ── Konstruksie & DHS ──
  { id: "c1", sku: "CN-CEM-50",     naam: "Sement PPC 50kg Sak",                     naamEn: "Cement PPC 50kg Bag",                       kategorie: "konstruksie", handelsmerk: "PPC",            prys: 119.0,  voorraad: true,  topverkoper: true,  beskrywing: "CEM II 32.5N algemene-doel sement.",                                              beskrywingEn: "CEM II 32.5N general purpose cement.",                                         beeldUrl: "https://images.pexels.com/photos/29817952/pexels-photo-29817952.jpeg" },
  { id: "c2", sku: "CN-RIVER-40",   naam: "Riviersand 40kg Sak",                     naamEn: "River Sand 40kg Bag",                       kategorie: "konstruksie", handelsmerk: "Generies",       prys: 49.0,   voorraad: true,                      beskrywing: "Gewaste riviersand vir messelwerk en pleister.",                                  beskrywingEn: "Washed river sand for brickwork and plaster.",                                 beeldUrl: "https://images.pexels.com/photos/6473974/pexels-photo-6473974.jpeg" },
  { id: "c3", sku: "CN-BRICK-CLAY", naam: "Stockbaksteen (per 100)",                 naamEn: "Stock Brick (per 100)",                     kategorie: "konstruksie", handelsmerk: "Generies",       prys: 365.0,  voorraad: true,                      beskrywing: "Standaard kleisteen, NHBRC voldoende.",                                           beskrywingEn: "Standard clay brick, NHBRC compliant.",                                        beeldUrl: "https://images.pexels.com/photos/1101125/pexels-photo-1101125.jpeg" },
  { id: "c4", sku: "CN-PLAS-25",    naam: "Gipspleister 25kg",                       naamEn: "Plaster of Paris 25kg",                     kategorie: "konstruksie", handelsmerk: "Cretestone",     prys: 139.0,  voorraad: false,                     beskrywing: "Binnemuur gipspleister vir gladde afwerking.",                                    beskrywingEn: "Interior wall plaster for smooth finish.",                                     beeldUrl: "https://images.pexels.com/photos/11700775/pexels-photo-11700775.jpeg" },
  { id: "c5", sku: "CN-RHEEM-38",   naam: "Rheinzink Plafonboard 6.4mm",             naamEn: "Gypsum Ceiling Board 6.4mm",                kategorie: "konstruksie", handelsmerk: "Gyproc",         prys: 189.0,  voorraad: true,                      beskrywing: "Gipsplafonbord, 3.0m x 1.2m vel.",                                               beskrywingEn: "Gypsum ceiling board, 3.0m x 1.2m sheet.",                                    beeldUrl: "https://images.pexels.com/photos/29519165/pexels-photo-29519165.jpeg" },
  { id: "c6", sku: "CN-PINE-38",    naam: "Greinhout Plank 38x38mm (per meter)",     naamEn: "Pine Plank 38x38mm (per metre)",            kategorie: "konstruksie", handelsmerk: "Generies",       prys: 28.5,   voorraad: true,                      beskrywing: "Gedroogde grenehout, geskaaf.",                                                   beskrywingEn: "Dried pine wood, planed.",                                                     beeldUrl: "https://images.pexels.com/photos/35966955/pexels-photo-35966955.jpeg" },

  // ── Verf & Gereedskap ──
  { id: "v1", sku: "VF-PVA-20",    naam: "PVA Muurverf 20L (Wit)",                  naamEn: "PVA Wall Paint 20L (White)",                kategorie: "verf",        handelsmerk: "Dulux",          prys: 749.0,  voorraad: true,  topverkoper: true,  beskrywing: "Binnemuur PVA — vra ons oor kleurmenging op bestelling.",                        beskrywingEn: "Interior PVA — ask us about custom colour mixing on request.",                 beeldUrl: "https://images.pexels.com/photos/5642093/pexels-photo-5642093.jpeg" },
  { id: "v2", sku: "VF-ENAM-5",    naam: "Emaljeverf 5L (Hoogglans)",               naamEn: "Enamel Paint 5L (High Gloss)",              kategorie: "verf",        handelsmerk: "Plascon",        prys: 689.0,  voorraad: true,                      beskrywing: "Universele emaljeverf vir hout en metaal.",                                       beskrywingEn: "Universal enamel paint for wood and metal.",                                   beeldUrl: "https://images.pexels.com/photos/5641684/pexels-photo-5641684.jpeg" },
  { id: "v3", sku: "VF-BRUSH-75",  naam: "Verfkwas 75mm",                           naamEn: "Paint Brush 75mm",                          kategorie: "verf",        handelsmerk: "Harris",         prys: 79.9,   voorraad: true,                      beskrywing: "Sintetiese vesel kwas vir glad afwerking.",                                       beskrywingEn: "Synthetic fibre brush for smooth finish.",                                     beeldUrl: "https://images.pexels.com/photos/5641409/pexels-photo-5641409.jpeg" },
  { id: "v4", sku: "VF-ROLL-230",  naam: "Rollerstel 230mm met Bak",                naamEn: "Roller Set 230mm with Tray",                kategorie: "verf",        handelsmerk: "Academy",        prys: 119.0,  voorraad: true,                      beskrywing: "Verfrollerstel met handvatsel en bak.",                                           beskrywingEn: "Paint roller set with handle and tray.",                                       beeldUrl: "https://images.pexels.com/photos/5583052/pexels-photo-5583052.jpeg" },
  { id: "v5", sku: "VF-DRILL-650", naam: "Slagboor 650W",                           naamEn: "Impact Drill 650W",                         kategorie: "verf",        handelsmerk: "Ingco",          prys: 649.0,  voorraad: true,  topverkoper: true,  beskrywing: "13mm slagboor met snelheidsbeheer — Ingco.",                                      beskrywingEn: "13mm impact drill with speed control — Ingco.",                                beeldUrl: "https://images.pexels.com/photos/3877525/pexels-photo-3877525.jpeg" },
  { id: "v6", sku: "VF-GRIND-115", naam: "Hoekslyper 115mm 750W",                   naamEn: "Angle Grinder 115mm 750W",                  kategorie: "verf",        handelsmerk: "Ingco",          prys: 549.0,  voorraad: true,                      beskrywing: "Kompakte hoekslyper vir sny en slyp.",                                            beskrywingEn: "Compact angle grinder for cutting and grinding.",                               beeldUrl: "https://images.pexels.com/photos/4315559/pexels-photo-4315559.jpeg" },

  // ── Loodgieter ──
  { id: "l1", sku: "LG-PVC-110",  naam: "PVC Rioolpyp 110mm (per 6m)",              naamEn: "PVC Sewer Pipe 110mm (per 6m)",             kategorie: "loodgieter",  handelsmerk: "Marley",         prys: 389.0,  voorraad: true,                      beskrywing: "Swaar-diens rioolpyp, SABS gemerk.",                                              beskrywingEn: "Heavy-duty sewer pipe, SABS marked.",                                          beeldUrl: "https://images.pexels.com/photos/12142829/pexels-photo-12142829.jpeg" },
  { id: "l2", sku: "LG-TAP-MX",   naam: "Mengkraan Wastafel Chroom",                naamEn: "Basin Mixer Tap Chrome",                    kategorie: "loodgieter",  handelsmerk: "Cobra",          prys: 549.0,  voorraad: true,  topverkoper: true,  beskrywing: "Enkelhefboom mengkraan, 5 jaar waarborg.",                                        beskrywingEn: "Single lever mixer tap, 5 year warranty.",                                     beeldUrl: "https://images.pexels.com/photos/30560253/pexels-photo-30560253.jpeg" },
  { id: "l3", sku: "LG-GEY-150",  naam: "Geyser-element 2kW (Universeel)",          naamEn: "Geyser Element 2kW (Universal)",            kategorie: "loodgieter",  handelsmerk: "Kwikot",         prys: 219.0,  voorraad: true,                      beskrywing: "Vervangingselement vir 150L geyser.",                                             beskrywingEn: "Replacement element for 150L geyser.",                                         beeldUrl: "https://images.pexels.com/photos/67184/pexels-photo-67184.jpeg" },
  { id: "l4", sku: "LG-FLEX-15",  naam: "Buigpyp 15mm x 600mm",                    naamEn: "Flexible Pipe 15mm x 600mm",                kategorie: "loodgieter",  handelsmerk: "Cobra",          prys: 89.0,   voorraad: true,                      beskrywing: "Vlekvrye staal gevlegte verbindingspyp.",                                         beskrywingEn: "Stainless steel braided connector pipe.",                                      beeldUrl: "https://images.pexels.com/photos/36571568/pexels-photo-36571568.jpeg" },
  { id: "l5", sku: "LG-TRAP-40",  naam: "Bottelstrik 40mm",                         naamEn: "Bottle Trap 40mm",                          kategorie: "loodgieter",  handelsmerk: "Marley",         prys: 69.9,   voorraad: false,                     beskrywing: "PVC bottelstrik vir wasbak afvoer.",                                              beskrywingEn: "PVC bottle trap for basin outlet.",                                            beeldUrl: "https://images.pexels.com/photos/14598653/pexels-photo-14598653.jpeg" },

  // ── Gasprodukte ──
  { id: "g1", sku: "GS-REF-9",    naam: "LP-Gas Hervulling 9kg",                    naamEn: "LP Gas Refill 9kg",                         kategorie: "gas",         handelsmerk: "Afrox / Totalgaz", prys: 399.0, voorraad: true,  topverkoper: true,  beskrywing: "9kg gasbottel hervulling — bring jou leë bottel in.",                             beskrywingEn: "9kg gas cylinder refill — bring your empty cylinder in.",                      beeldUrl: "https://images.pexels.com/photos/29848733/pexels-photo-29848733.jpeg" },
  { id: "g2", sku: "GS-REF-19",   naam: "LP-Gas Hervulling 19kg",                   naamEn: "LP Gas Refill 19kg",                        kategorie: "gas",         handelsmerk: "Afrox / Totalgaz", prys: 799.0, voorraad: true,                      beskrywing: "19kg gasbottel hervulling vir groter verbruik.",                                  beskrywingEn: "19kg gas cylinder refill for larger consumption.",                             beeldUrl: "https://images.pexels.com/photos/16271901/pexels-photo-16271901.jpeg" },
  { id: "g3", sku: "GS-REG-LP",   naam: "Gasreguleerder Laagdruk",                  naamEn: "Low Pressure Gas Regulator",                kategorie: "gas",         handelsmerk: "Cadac",          prys: 159.0,  voorraad: true,                      beskrywing: "Laagdruk reguleerder met klembeslag.",                                            beskrywingEn: "Low pressure regulator with clamp fitting.",                                   beeldUrl: "https://images.pexels.com/photos/36285352/pexels-photo-36285352.jpeg" },
  { id: "g4", sku: "GS-HOSE-2M",  naam: "Gaspyp 2m met Klemme",                    naamEn: "Gas Pipe 2m with Clamps",                   kategorie: "gas",         handelsmerk: "Cadac",          prys: 119.0,  voorraad: true,                      beskrywing: "SABS gemerkte gaspyp met twee slangklemme.",                                      beskrywingEn: "SABS marked gas pipe with two hose clamps.",                                   beeldUrl: "https://images.pexels.com/photos/27741082/pexels-photo-27741082.jpeg" },
  { id: "g5", sku: "GS-2PLATE",   naam: "Gasstofie 2-Plaat Tafel",                  naamEn: "2-Plate Gas Stove Tabletop",                kategorie: "gas",         handelsmerk: "Totai",          prys: 749.0,  voorraad: true,                      beskrywing: "2-plaat gasstofie met veiligheidsklep.",                                          beskrywingEn: "2-plate gas stove with safety valve.",                                         beeldUrl: "https://images.pexels.com/photos/13422435/pexels-photo-13422435.jpeg" },
];

export const topVerkopers = () => PRODUKTE.filter((p) => p.topverkoper);
